### PR TITLE
Web pages are ready

### PR DESCRIPTION
**Pull request by thevulch**
I think I got the web pages working, but we should make sure before merging into master. Primarily, we need to decide which browsers we support. I've been using some ES6 stuff (template strings, `let` declaration), but we might need to rewrite it to ES5 for older browser support.

### CODE REVIEW

**Comment by TheVulch** [comment]
@qubotong should we close #9 ? I think that PR was set to merge the wrong way...

**Comment by qubotong** [comment]
Hey @TheVulch, 

I tested with following codes, add them to the index.html to see if we could get the right result.
		let test_hypergeo1 = stats.hypergeometric(1,10,12,24);
		let test_fisher1 = stats.fisher(1,10,12,24);
		let test_chi1 = stats.chi(1,10,12,24); 

Unfortunately, the result is not as same as the document states, have you test your new methods? I checked your codes in the bundle.js, it look like correct for me, but why the result is different?

**Comment by qubotong** [comment]
Also, I checked with the AgriGO, It looks like our calculation results is different from theirs...

**Comment by TheVulch** [comment]
@qubotong you can see my tests in the statistics/test.js file...everything works on my end. could you add your tests to the repo and i can see whats going on?

**Comment by TheVulch** [comment]
@qubotong i forgot to refresh the bundle.js in project/js . For the tests you added, we get:
```
hyper: 0.0013460761879122358 
fisher: 0.0013797280926100418 
chi: 0.0004993016856344503
```
That looks right to me...right? The chi-square test p value wasn't given in the document, but it is below 0.001, which is what the document stated.

**Comment by thevulch** [comment]
@qubotong I'm going to merge this later, but first I want to make sure - we don't need master branch for anything right?

**Comment by qubotong** [comment]
@thevulch Yeah, I think all my work is on the webpage branch, so after fixing all bugs, we could merge this branch

**Pull request merged**
